# Generated by Django 6.0.2 on 2026-02-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_options_alter_productvariant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['-is_default', 'size']},
        ),
    ]
