# Generated by Django 6.0.2 on 2026-02-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_price_productvariant_original_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
