# Generated by Django 6.0.2 on 2026-03-04 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_cart_user_alter_cartitem_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_mode', models.CharField(blank=True, choices=[('FULL', 'Full Payment'), ('PARTIAL', '50% Advance')], max_length=20, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance_enabled', models.BooleanField(default=False)),
                ('final_enabled', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Address Pending', 'Address Pending'), ('Waiting Approval', 'Waiting Approval'), ('Payment Pending', 'Payment Pending'), ('Partially Paid', 'Partially Paid'), ('Fully Paid', 'Fully Paid'), ('Completed', 'Completed')], default='Address Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
