# Generated by Django 6.0.2 on 2026-02-25 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
