# Generated by Django 6.0.2 on 2026-03-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_bannerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HappyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='customers/')),
                ('rating', models.IntegerField(default=5)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
