# Generated by Django 6.0.3 on 2026-03-05 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_enquiry'),
        ('customer', '0008_happycustomer'),
    ]

    operations = [
    ]
